log_format json_combined escape=json
    '{'
    '"time":"$time_iso8601",'
    '"remote_addr":"$remote_addr",'
    '"status":"$status",'
    '"method":"$request_method",'
    '"uri":"$request_uri",'
    '"bytes":$body_bytes_sent,'
    '"ref":"$http_referer",'
    '"request_id":"$request_id"'
    '}';

access_log /dev/stdout json_combined;

limit_req_zone $binary_remote_addr zone=main:10m rate=30r/s;
